### ISSUE TITLE
Correct the layout on the pages of the creation and editing of the vacancy

### ISSUE THREAD

**Issue by ToshiDono** [howtohireme/juniorjobs#133]
1. баг отображения тегов:
![Screenshot at янв. 30 12-09-42.png](https://images.zenhubusercontent.com/5a63bb864b5806bc2bc38ed7/9422d641-2b6f-4c76-a309-a03bcf4aab31)

2. Предлагаю выровнять по горизонтали, чтобы "до" начинались на одном уровне(т.е. добавить отступы):
![Screenshot at янв. 30 12-10-29.png](https://images.zenhubusercontent.com/5a63bb864b5806bc2bc38ed7/4fae8f13-7daf-4c71-acfc-99c6997eab07)

3. Очень не удобно пользоваться стрелками. Они очень маленькие, нужно изменить.
4. Нужно запретить вводить или "накликивать" отрицательные значения.
![Screenshot at янв. 30 12-10-55.png](https://images.zenhubusercontent.com/5a63bb864b5806bc2bc38ed7/20382fcd-54b8-42f8-b471-5b9034348e7b)

**Comment by ToshiDono** [comment]
@dborovsky нужно будет дописать тесты создания вакансии -добавить туда использование тегов и "стрелок".

**Comment by khusnetdinov** [comment]
1,3,4 пофиксил в другом MR. 2 Пусть пока так
